pipeline:
  build:
    image: microsoft/dotnet
    commands:
      - dotnet restore
      - dotnet build
      - dotnet test ./CheekyTests/CheekyTests.csproj
  run:
    image: microsoft/dotnet
    commands:
      - dotnet restore
      - dotnet build
      - dotnet run Debug -p ./CheekyMonkey/CheekyMonkey.csproj
