version: 2
jobs:
  test:
    docker:
      - image: microsoft/dotnet
    steps:
      - checkout
      - run:
          name: restore
          command: dotnet restore ./CheekyTests/CheekyTests.csproj
      - run:
          name: build
          command: dotnet build ./CheekyTests/CheekyTests.csproj
      - run:
          name: test
          command: dotnet test ./CheekyTests/CheekyTests.csproj
  docker-image:
    machine: true
    context: CheekyMonkey
    steps:
      - checkout
      - run:
          name: docker-image
          command: |
            TAG=latest
            IMAGE=application_name
            docker build -t $IMAGE:$TAG .
            docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            docker tag $IMAGE:$TAG $DOCKER_REGISTRY/$IMAGE:$TAG
            docker push $DOCKER_REGISTRY/$IMAGE:$TAG
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - docker-image:
          requires:
            - test
