resources:
- name: sourcecode
  type: git
  source:
    uri: https://github.com/petegee/CheekyMonkey.git

- name: app-docker-image
  type: docker-image
  source:
    email: peteg@hotmail.co.nz
    username: peteg
    password: ((docker-hub-password))
    repository: peteg/cheekymonkey
    
jobs:
- name: job-build-and-publish-docker-image
  plan:
  - get: sourcecode
    trigger: true
  - put: app-docker-image
    params:
      build: sourcecode
   
  - task: build-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {microsoft/dotnet}

      inputs:
      - name: sourcecode
      outputs:
      - name: app

      run:
        path: sh
        args: ["sourcecode/ci/build.sh"]


  - task: build-docker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {microsoft/dotnet}

      inputs:
      - name: app
      outputs:
      - name: app-docker-image
