resources:
- name: sourcecode
  type: git
  source:
    uri: https://github.com/petegee/CheekyMonkey.git

- name: hello-world-docker-image
  type: docker-image
  source:
    email: peteg@hotmail.co.nz
    username: peteg
    password: ((docker-hub-password))
    repository: peteg/cheekymonkey
    

jobs:
- name: job-build-and-test-app
  plan:
  - get: sourcecode
    trigger: true 
  - put: sourcecode
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: microsoft/dotnet
      inputs:
      - name: sourcecode
      run:
        path: sh
        args: ["sourcecode/ci/test.sh"]

- name: publish
  plan:
  - get: sourcecode
  - put: hello-world-docker-image
    params:
      build: sourcecode