resources:
- name: sourcecode
  type: git
  source:
    uri: https://github.com/petegee/CheekyMonkey.git
    
jobs:
- name: BuildDockerImage
  plan:
  - get: sourcecode
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: microsoft/dotnet}
      run:
        path: sh
        args: ["sourcecode/ci/build.sh"]