resources:
- name: source_code
  type: git
  source:
    uri: git@github.com:petegee/CheekyMonkey.git
    branch: master

jobs:
- name: BuildDockerImage
  plan:
  - get: source_code
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: microsoft/dotnet}
      run:
        path: sh
        args: ["source_code/ci/build.sh"]