resources:
- name: sourcecode
  type: git
  source:
    uri: https://github.com/petegee/CheekyMonkey.git

jobs:
- name: BuildDockerImage
  plan:
  - get: sourcecode
    trigger: true
  - task: build
    file: sourcecode/build.yml