resources:
- name: sourcecode
  type: git
  source:
    uri: https://github.com/petegee/CheekyMonkey.git

jobs:
- name: job-build-and-test-app
  plan:
  - get: sourcecode
    trigger: true
  - task: build-app
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: microsoft/dotnet

      inputs:
      - name: sourcecode

      run:
        path: sh
        args: ["sourcecode/ci/build.sh"]